# Generated by Django 4.1 on 2023-02-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_tb',
            new_name='sregister_tb',
        ),
    ]
