# Generated by Django 4.1 on 2023-02-10 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_tb_details'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingaddress', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.register_tb')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb')),
            ],
        ),
    ]
