# Generated by Django 4.1 on 2023-02-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_order_tb_orderitem_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tb',
            name='orderdate',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order_tb',
            name='ordertime',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
