# Generated by Django 4.1 on 2023-02-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_category_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_tb',
            old_name='name',
            new_name='cname',
        ),
    ]
